### ISSUE TITLE
Write the CSV after each game; generate XML from CSV in second phase.

### ISSUE THREAD

**Issue by slothbear** [slothbear/armor_games#12]
Any error in the scrapers or environment (network) can cause the program to stop—and lose all of the work done so far. Depending on how many games are in the run and how nice you'd like to be to the source server, re-running the program can take a lot of time and server hits.

Consider each game to the CSV as its finished (`csv.flush`). Once the CSV is complete, use it to generate the XML. Since we're not holding anything in memory, the `gameset` and `game` collections can be eliminated.

There could be two kinds of re-run:
* Skip accessing the game server; just convert the CSV to XML again. This would allow small tweaks to the CSV to generate new XML without hitting the server.
* Start the run in the middle somewhere. Page X, Tile Y. This would require reporting how far the run got—any some kind of command line arguments for specifying where to start the re-run. 

Instead of command line arguments to control the re-run, the script could be edited to change the phase and  magic numbers. But the game sites have different ways of organizing the games. On some sites, it would be as easy as "start with game 702". On paged sites, it would require something more complicated like "start on page 4, game 22". I feel I'm missing some idea that would simplify the re-runs.

**Comment by slothbear** [comment]
Re-open if this enhancement becomes a requirement.

**Comment by slothbear** [comment]
@ErinPettigrew Do you think this is something I should be thinking about? The question boils down to: do I run the scrapers — as I've done so far and I'm happy to continue — or might someone else be running them too? A while back Greg Brockman mentioned he was running the Armor scraper.

This isn't a big deal for me... I do a smoke test run that picks a bunch of random games and I'm pretty confident that the full run will be ok. And if it's not, I fix it and re-run. I could see it being a big bummer for someone else though who has let the scraper run for hours then bombs on the last game. And the older a scraper becomes, the more likely some small change at the source site will cause an error.

It's a reasonable amount of work (bigger than a breadbox) to make the scrapers more resilient in this fashion. My recommendation: wait for the first time it get Really Annoying, then consider our options.

**Comment by erinpettigrew** [comment]
@slothbear Our priority right now is getting as many games as possible scraped as quickly as possible. So I would say this enhancement, if it's decided to be needed later, could be worked on after.

The workflow with you running the scraper and generating the files is working great for this part. I also don't foresee the content from these sites changing all that often such that your original exports would become outdated. The games seem here to stay.

My two cents!
