### ISSUE TITLE
Update Kongregate scraper to retrieve flash_file

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#18]
(Hi Paul!)

We need the Kongregate games .csv updated with the flash file for each game. 

Can you update the scraper and resulting xml / csv outputs with all of those .swfs in the flash_file field?

**Comment by slothbear** [comment]
I've had trouble getting the flash file name for the Kongregate non-free racing games. As far as I could see before, the flash_file appeared to be constructed from some kind of script handshake between the browser and the server. But I just tried again (n-th time's a charm ❓ ) and in a couple cases I found something in the source that might work.

The `flash_file` field is already an outstanding item in issue #9 — so I'd like to continue to track it there — unless I'm off the mark and you were pointing to another area with this issue.
