### ISSUE TITLE
Armor - overlap of racing games and free to use games

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#19]
For Armor -- Are you able to quickly produce a csv list of the overlapping entries between the free games (~1400) and racing games (~100)?

**Comment by slothbear** [comment]
14 games are common to both Armor free and Armor non-free racing, listed in armor_overlaps.csv.

https://github.com/slothbear/armor_games/blob/master/armor_overlaps.csv

**Comment by erinpettigrew** [comment]
Huge help, thanks!
