### ISSUE TITLE
Create a scraper for freegamesforyourwebsite.com

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#20]
64 free racing games:
http://www.freegamesforyourwebsite.com/tag/racing

Fields needed (if available):

- [x]  title
- [x]  url
- [x]  flash_file
- [x] description
- [ ]  developer_name _(not found in visible page or source)_

#### added for consistency with other game sites, if available:

- [x] thumbnail
- [x] width
- [x] height
- [x] category

**Comment by slothbear** [comment]
For the other scrapers, we also tried to collect:
- thumbnail
- width & height of flash_file

Are those not needed for this scraper?

**Comment by slothbear** [comment]
The flash width and height might be tricky for some scrapers. Often the game is in multiple containers of varying sizes. I've tried to select what seems the most native size — but I think in some cases the game is being shown larger or smaller than the native size.

**Comment by erinpettigrew** [comment]
@nottombrown do we need thumbnail and height / width of Flash file for all scraped games?

**Comment by slothbear** [comment]
I apologize I didn't include some context — which was in the original request but never explicitly made it into an issue, though Armor Games thumbnails were covered in Issue #2.

From Tom's Phase 2 request for tags, thumbnails, notdoppler, and miniclip:
> 1) Add 'tags' and 'thumbnail' to the scraped armorgames xml
> It looks like there are a bunch of tags on armorgames, could you bring them in?
![image](https://cloud.githubusercontent.com/assets/13285/18369972/379df044-75f7-11e6-865a-71ef938e85e0.png)
> We're also now making pretty little README's so it would be nice to have a thumbnail.
https://github.com/openai/gym-vnc-envs-build/tree/master/public/kaboomz-3

**Comment by erinpettigrew** [comment]
Got it! Go ahead and bring in all the originally requested data then. You got it!

**Comment by erinpettigrew** [comment]
Tom adds though that if these extra fields slow down your scraping progress for any particular sites, it's okay to skip them.

**Comment by slothbear** [comment]
A list by priority is extremely helpful to me, thanks. I'm awash in a sea of details from many sites... so it's great to know where to focus first. I've created a wiki page to list the must-have fields vs. nice-to-haves. 

https://github.com/slothbear/armor_games/wiki

**Comment by slothbear** [comment]
48 Flash games were found.

Of the 64 games, 14 appear to be Unity games, so no flash_file is available. Two games (_Formula Fog_ and _Street Racer_) are listed as a Flash games but don't load in the browser.

The only thing I couldn't find is the developer name. I searched the visible text and page source… no trace of dev name that I can find.

**Comment by erinpettigrew** [comment]
Thanks. Closing this one.
