### ISSUE TITLE
Create a scraper for Willing Games

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#21]
2284 not-free racing games:
http://www.willinggames.com/racing-games/

Fields needed (if available):

- [x]  title
- [x]  url
- [x]  flash_file
- [x] description
- [x]  developer_name (aka 'author' in the metadata)

Additional useful fields:

- [x] thumbnail
- [x] width
- [x] height
- [x] category

**Comment by slothbear** [comment]
As before, I'm skipping the `flash_file` for Unity3D games. 

I've noticed several game embed URLs that are malformed. This appears to be an error in the way they are embedding HTML5 games, which I've also skipped. The scraper is running now… let's see how many games we get.

**Comment by erinpettigrew** [comment]
This was hugely helpful since the site had so many games.

I think the .dcr files are Shockwave files. What you did makes sense.
