### ISSUE TITLE
Create a scraper for Y8

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#22]
1475 not-free racing games:
http://www.y8.com/tags/Racing

Fields needed (if available):

- [x] title
- [x] url
- [x] flash_file
- [x] description
- [ ] developer_name (not seeing in source code)

Additional useful fields:

- [x] thumbnail
- [x] width
- [x] height
- [x] category

**Comment by slothbear** [comment]
There's a conditional template in the `Comments` section that could display a developer's name and avatar, but I've not seen it filled in any game I've looked at so far.

![image](https://cloud.githubusercontent.com/assets/13285/18413287/4e16dee6-7771-11e6-95a6-41f038695936.png)

**Comment by slothbear** [comment]
Some of the game files end in `.dcr`, even though they're labeled as Flash. I tried one in the browser and received the error message "Director plugin not supported". I suspect this is the same DCR I found in WillingGames (#21).

**Comment by slothbear** [comment]
I don't know what their definition of **Free** is, but most of the games include a "Free" tag:

![image](https://cloud.githubusercontent.com/assets/13285/18414380/70a8b0d4-7793-11e6-8a0b-551fac9c7a12.png)

http://www.y8.com/games/the_fast_and_the_phineas

**Comment by slothbear** [comment]
The output includes 1491 games, of which 1146 have a valid `flash_file` value. The rest are Unity3D, Director, HTML5, or other.

The Director games have a value of `7` in the flash_file field (with `11` or `12` in a few for variety). If that's a problem let me know and I can clean it up.

Still no sign of the developer's name.

**Comment by erinpettigrew** [comment]
Huge help, thanks. 

I'll get the game reviewer to manually add in the developer name (not ideal but a must for non-free game that don't include dev info in the source code).

I don't think the value of 7 will be an issue since those file types likely aren't valid for our use anyway.
