### ISSUE TITLE
Create a scraper for Car Titans

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#23]
http://www.cartitans.com/free-car-games/

Same needs as before, thanks!

field list [in order of importance](https://github.com/slothbear/armor_games/wiki). I check them off as I find them and add them to the scraper, pending the full run at the end.

- [x] flash_file (`.swf` file)
- [x] title
- [x] url (to play the game)
- [x] description
- [ ] developer_name
- [x] thumbnail
- [x] category/tags
- [x] width (for `flash_file`)
- [x] height (for `flash_file`)

**Comment by slothbear** [comment]
field list [in order of importance](https://github.com/slothbear/armor_games/wiki). I check them off as I find them and add them to the scraper, pending the full run at the end.

- [ ] flash_file (`.swf` file)
- [ ] title
- [ ] url (to play the game)
- [ ] description
- [ ] developer_name
- [ ] thumbnail
- [ ] category/tags
- [ ] width (for `flash_file`)
- [ ] height (for `flash_file`)

**Comment by slothbear** [comment]
What a cake walk. Everything nicely structured and no extra massaging needed. I expect all 161 games to come through. I'll do the full run as soon as I get home to a stable network connection this afternoon.

**Comment by slothbear** [comment]
No problems. 161 new games, and every one I tried worked fine.

I especially loved playing the bus driver in the snow. But now I can't find it again. they all look alike!

**Comment by erinpettigrew** [comment]
+1 for correcting the name of this issue to 'Car Titans.' It's the little things!

We shall remember this one as the most beautiful scrape in the racing game world.

Closing!
