### ISSUE TITLE
Create scraper for Turbonuke

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#24]
http://www.turbonuke.com/addgame.php

field list [in order of importance](https://github.com/slothbear/armor_games/wiki). Paul checks them off as as found and added  to the scraper, pending the full run at the end.

- [x] flash_file (`.swf` file)
- [x] title
- [x] url (to play the game)
- [x] description
- [ ] developer_name
- [x] thumbnail
- [x] category/tags
- [x] width (for `flash_file`)
- [x] height (for `flash_file`)

**Comment by slothbear** [comment]
field list [in order of importance](https://github.com/slothbear/armor_games/wiki). I check them off as I find them and add them to the scraper, pending the full run at the end.

- [ ] flash_file (`.swf` file)
- [ ] title
- [ ] url (to play the game)
- [ ] description
- [ ] developer_name
- [ ] thumbnail
- [ ] category/tags
- [ ] width (for `flash_file`)
- [ ] height (for `flash_file`)

**Comment by slothbear** [comment]
50 games added from Turbonuke.

**Comment by erinpettigrew** [comment]
Great, thanks.
