### ISSUE TITLE
Create a scraper for SpilGames (free to use)

### ISSUE THREAD

**Issue by erinpettigrew** [slothbear/armor_games#26]
http://publishers.spilgames.com/en/catalog#s_category=Racing&s_pageIndex=1&section=Search

field list in order of importance

- [x]  flash_file (.swf file)
- [x]  title
- [ ]  url (to play the game)
- [x]  description
- [ ]  developer_name
- [x]  thumbnail
- [x]  category/tags
- [x]  width (for flash_file)
- [x]  height (for flash_file)

111 free to use games! This might be a nice one to tackle if you need a break from thinking about Bored.

**Comment by slothbear** [comment]
😸  It's hard to believe I never knew this genre existed, and continue to be surprised by how large it is. This site prepackages thumbnails in small, medium, and large.  I suppose I should grab large, since the destination could always resize down. Dinosaurs mowing lawns. Gotta get me one of those.

![image](https://cloud.githubusercontent.com/assets/13285/18522616/bf82d82c-7a7e-11e6-98e1-4753cd724311.png)

**Comment by slothbear** [comment]
With some difficulty I've found everything except the `developer_name`. There are 77 flash games in the collection. The rest are HTML5, Unity or other non-Flash. I'm running the scraper now and should have results soon.

**Comment by slothbear** [comment]
I'm getting most game information from the site's rss feed — which hands me most of what we need without true scraping. But... the Description is just a sentence or two, and there are only two Categories listed — the game play page sometimes has additional Categories. Is it worth doing a full scraping for the full description and categories?

**Comment by slothbear** [comment]
Wow I've been so deep in this that I forgot my original difficulty — that the catalog pages are built in some dynamic way that I haven't been able to scrape yet.

So what I'm missing at the moment:
- `developer_name`
- full description (though I have brief description)
- all categories (I have two)
- `url`: the full "play" page that the user would go to. The rss feed that I'm reading only has the `flash_file`.

Should I go back to attempting a full scrape so I can get the Url, full description and all categories?

**Comment by erinpettigrew** [comment]
Cool! Because these are free to use, developer_name becomes less important (we use it to reach out to get permission).

So, I'd say you can produce this one with the fields you were able to get and then move on to another site.

Getting a ton of games right now is the first priority, breadth beyond critical fields is a nice to have for this one.

**Comment by slothbear** [comment]
I've added the data for the 77 flash games at Spilgames, minus the `developer_name` and `url`.

**Comment by erinpettigrew** [comment]
Thanks. Closing this one for now. If we need the url or any other fields, I will reopen.
