### ISSUE TITLE
Scrape in all the (non-free) racing games

### ISSUE THREAD

**Issue by nottombrown** [slothbear/armor_games#8]
We are going to manually ask developers for permission to use their racing flash games. 

Step one is to put all the racing games that we don't yet have permission for into a big spreadsheet:

- [ ] [Kongregate](http://www.kongregate.com/racing-games) - 740 racing games
- [ ] [Armor Games](http://armorgames.com/category/racing-games) - 70 racing games
- [ ] [notDoppler](http://www.notdoppler.com/sports.php) - 200 sports games
- [ ] [Miniclip](http://www.miniclip.com/webmasters/genre-477/racing/en/) - 70 games (although [50 of them are already free to use](http://www.miniclip.com/webmasters/genre-477/racing/en/))

After that, we'll contract out some people to find contact information for all the developers and get them to agree to let us use their games.

**Comment by nottombrown** [comment]
If you have ideas for these, let me know, @slothbear. I'll be planning on tackling them this afternoon. 

Particularly interested in finding a way to get all the miniclip games that are tagged racing.

**Comment by slothbear** [comment]
I haven't been able to find any developer names on miniclip. Well, I have seen credits _within_ the flash game itself, but I don't know if it's possible to get those... perhaps inside the flash file itself?

Or do you see the developer info somewhere else?

I started on notDoppler and hit a few snags... should I switch to Kongregate for now?

**Comment by nottombrown** [comment]
Yes please, Kongregrate seems like it's the most important. 

It's awesome if you can pull in developer names, but if you can't we'll mechanical turk it out.

**Comment by slothbear** [comment]
These scrapers now have individual issues for tracking their progress.

-  #9 Kongregate
-  #15 Armor Games
-  #11 notDoppler
-  #16 Miniclip
