### ISSUE TITLE
Create a scraper for Kongregate non-free racing games.

### ISSUE THREAD

**Issue by slothbear** [slothbear/armor_games#9]
Transferred from #8.

http://www.kongregate.com/racing-games

- [x] title
- [x] url
- [ ] description
- [x] thumbnail
- [x] developer_name
- [x] tags/category
- [x] flash_file
- [ ] width
- [ ] height

**Comment by slothbear** [comment]
Interesting tidbit: the first page says it is listing games 1-17, but there are actually 18 games in the grid. The first game in row two, labeled **GAME SPOTLIGHT** is actually a Google ad.

**Comment by slothbear** [comment]
I was able to find 5 of the 9 fields, but am still missing description, flash_file, width, height. As far as I can tell those values might be filled in via Javascript—which I could do but it would take more time and different techniques.

@nottombrown Are the current available fields of any use for the spreadsheet? I'm headed to dinner and will let the program run while I'm out and check back later.

**Comment by slothbear** [comment]
I think maybe Kongregate has a single _category_ for each game, plus multiple tags per game. There was some discussion of that on their forums, but I still can't find anything specific in the xml format.

**Comment by nottombrown** [comment]
That makes sense. Can we have two different xml values
- tags
- category

It's fine if there's overlap. In fact, `tags` should include the `category` for all games

**Comment by slothbear** [comment]
I can make separate XML element for tags and categor, But it's going to be pretty boring for this particular run. Since we're only scraping the Racing games, every category will be set to `Sports & Racing`.

**Comment by slothbear** [comment]
http://www.kongregate.com/racing-games now has 816 games.

I was able to discern the `flash_file` for 655 of those games, or 80%. The outliers I looked at so far all have different formats. Let me know the priority of those outliers vs. other game sources.

**Comment by erinpettigrew** [comment]
These have been great, thank you.

Okay to close (I don't have the option to in Github UI as you are the owner).

**Comment by slothbear** [comment]
Check out this link to become a collaborator on the repository. I think that will let you close my issues and probably anything else...
https://github.com/slothbear/armor_games/invitations
